name: CI Pipeline for Iris Dataset

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Updated to Python 3.9

      - name: Install Dependencies
        run: make install

      # Install CML to ensure it's available for model evaluation
      - name: Install CML
        run: pip install cml

      - name: Train Model
        run: make train

      - name: Format Code
        run: make format

      - name: Evaluate Model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval
